// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBasjPoFjetTtOxN0Jxha3jy4lXgnawV-I',
    appId: '1:159394190998:web:8d437b8c8a02d730a654b7',
    messagingSenderId: '159394190998',
    projectId: 'movie-browser-app-b5c9d',
    authDomain: 'movie-browser-app-b5c9d.firebaseapp.com',
    storageBucket: 'movie-browser-app-b5c9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt3-ZTviLCiTDKgTqsNqYhf5sIXoZ-trQ',
    appId: '1:159394190998:android:9edcfb4e80838535a654b7',
    messagingSenderId: '159394190998',
    projectId: 'movie-browser-app-b5c9d',
    storageBucket: 'movie-browser-app-b5c9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe4EpPIBJsVmxZ3xNx0hSZeMqlYMFCdkQ',
    appId: '1:159394190998:ios:6855c7d2e1fcb3ada654b7',
    messagingSenderId: '159394190998',
    projectId: 'movie-browser-app-b5c9d',
    storageBucket: 'movie-browser-app-b5c9d.appspot.com',
    iosBundleId: 'com.example.movieBrowser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe4EpPIBJsVmxZ3xNx0hSZeMqlYMFCdkQ',
    appId: '1:159394190998:ios:6855c7d2e1fcb3ada654b7',
    messagingSenderId: '159394190998',
    projectId: 'movie-browser-app-b5c9d',
    storageBucket: 'movie-browser-app-b5c9d.appspot.com',
    iosBundleId: 'com.example.movieBrowser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBasjPoFjetTtOxN0Jxha3jy4lXgnawV-I',
    appId: '1:159394190998:web:4264dd69a818a861a654b7',
    messagingSenderId: '159394190998',
    projectId: 'movie-browser-app-b5c9d',
    authDomain: 'movie-browser-app-b5c9d.firebaseapp.com',
    storageBucket: 'movie-browser-app-b5c9d.appspot.com',
  );
}
